name = "Untagged and Untitled"
author = "Joshua & Others"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e6a061c4a0b2887d061992ef6647f4388abdfbff92972a06ff1bf2df39b223d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
