name = "Untagged and Untitled"
author = "Joshua & Others"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76baf5589b2280f46abf5a4c57a5828c56dcc36eeb6d135985307b899f88d91c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
