name = "Untagged and Untitled"
author = "Joshua & Others"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db833d97f1781af91b581e929840ceb2ed52295c7be556278d0a9c949a41c56f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
